- README.md
added a line regarding installing ZenHub to track feature development.
> add zenhub details to README.md

- facilitation/02-what-is-labs/README.md
@springdo @acammies - please can you take a quick look at these facilitation notes and the slides it links to?
> add facilitation notes with link to slides

- exercises/1-the-manual-menace/README.md
@makentenza  - can you take a look
> rework of git lab section as per feedback

- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
- exercises/3-revenge-of-the-automated-testing/README.md
- exercises/4-an-enslaved-hope/README.md
- exercises/5-non-functionals-strike-back/README.md
- exercises/6-return-of-the-app-monitoring/README.md
- exercises/7-the-cluster-awakens/README.md
- exercises/8-the-last-unicorn-dev/README.md
Added slide deck links to each exercise.
> Slide deck links

- exercises/0-rogue-cluster/README.md
- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
- exercises/3-revenge-of-the-automated-testing/README.md
- exercises/4-an-enslaved-hope/README.md
- exercises/5-non-functionals-strike-back/README.md
- exercises/6-return-of-the-app-monitoring/README.md
- exercises/7-the-cluster-awakens/README.md
- exercises/8-the-last-unicorn-dev/README.md
Mostly cosmetic fixes, but also one spelling update within exercise code.
> Updates for spelling, grammar, and whitespace

- README.md
- facilitation/00-setup/README.md
- facilitation/01-kick-off-and-target-outcomes/README.md
- facilitation/02-social-contract/README.md
- facilitation/03-what-is-labs/README.md
- facilitation/04-retrospectives/README.md
- facilitation/06-event-storming/README.md
- facilitation/08-vsm-and-mbpm/README.md
- facilitation/11-pairing-and-mobbing/README.md
- facilitation/99-wrap-up/README.md
As promised, I've added in a few notes based on the feedback and experience of the Tyson's Corner and London Enablement sessions.
@mtakane and @sudhakarau1 - i think it's worth you both reviewing with the upcoming NA and APAC sessions in mind. Happy to chat through anything.
> Post london session updates to facilitation notes

- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
- exercises/3-revenge-of-the-automated-testing/README.md
- exercises/4-an-enslaved-hope/README.md
- exercises/5-non-functionals-strike-back/README.md
- exercises/6-return-of-the-app-monitoring/README.md
- exercises/README.md
Tried to leave things alone semantically but just tidied up for easier readability.
> FIXED: more grammar/spelling typos.

- exercises/README.md
Learning from Singapore session.
> Refine pre-requisite subsection. 

- exercises/1-the-manual-menace/README.md
... using work-appropriate language. Resolves #254 (hopefully for reals, this time! :smile: )
> Restore Jenkins blog link

- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
- exercises/3-revenge-of-the-automated-testing/README.md
- exercises/4-an-enslaved-hope/README.md
- exercises/5-non-functionals-strike-back/README.md
- exercises/README.md
Modify hardcoded info around 'lader' DNS name and adapt documentation for the new name convention to be used with the Enablement Clusters.
> Adapt documentation for the new name convention

- slides/README.adoc
We used these instructions to generate PDF for the most recent DO500 run.
CC @tdbeattie @mtakane
> Add print instructions

- exercises/1-the-manual-menace/README.md
YOUR_NAME vs YOUR-NAME in the examples, so search-replace works better.
> fix naming consistency

- slides/markdown/chapter04.md
> created takeaways for mobbing and pairing and added video

- slides/markdown/chapter05.md
Fixes https://github.com/rht-labs/enablement-docs/issues/335
> Add additional popular retrospective formats

- slides/markdown/chapter09.md
I would like to suggest a New Slide for a summary with a content similar to this example.
I think is important to glue the 3 practice and summarize before presenting the next LAB.
> New slide for a summary for CI/CD/Deployment (chapter 09)

- exercises/1-the-manual-menace/README.md
resolves #346 
@springdo @eformat @gsampaio-rh FYI
> First cut at eliminating the need for branches

- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
related to PR https://github.com/rht-labs/enablement-ci-cd/pull/41
@springdo @tylerauerbeck @eformat @gsampaio-rh
> Updated exercise docs to reflect changes for namespace_prefix

- exercises/5-non-functionals-strike-back/README.md
@oybed @tylerauerbeck @eformat @springdo
> Replacing todolist-fe and todolist-api with todolist

- exercises/4-an-enslaved-hope/README.md
- exercises/5-non-functionals-strike-back/README.md
- exercises/6-return-of-the-app-monitoring/README.md
@springdo @oybed @eformat @tylerauerbeck
> Adding 📝  to files on ex4, 5 and 6

- slides/markdown/chapter09.md
> fix chapter 9 so all slides are flat

- slides/markdown/chapter07.md
> removed scrum image title issue #409

- slides/markdown/chapter05.md
- slides/markdown/chapter09.md
- slides/markdown/chapter12.md
- slides/markdown/chapter15.md
Issue: https://github.com/rht-labs/enablement-docs/issues/405
> Removed parking lot slides

- slides/markdown/chapter07.md
Issue: https://github.com/rht-labs/enablement-docs/issues/408
> changing slide title for Agile Overview

- slides/markdown/chapter02.md
> fixed spelling ch2 title slide issue #402

- slides/markdown/chapter01.md
> removed feedback loop slide from ch1 issue #397

- slides/markdown/chapter01.md
> removed death by ppt stuff ch1 issue #395

- slides/markdown/user_story_mapping.md
resolves https://github.com/rht-labs/enablement-docs/issues/415
> fixed video for value slicing

- slides/markdown/kick_off_and_target_outcomes.md
Issue: https://github.com/rht-labs/enablement-docs/issues/399
> fixed the room and the walls slide in the kickoff deck

- slides/markdown/estimation.md
resolves #459 
MVP content for the exercise and explanation of what is Estimation.
> filled in slide content for estimation

- exercises/1-the-manual-menace/README.md
Fixed some spacing issues with the `params_from_vars` yaml and removed mentions of Cows not being included (🐄as they are now included 🐄)
> Fixed Spacing; Cows now included

- slides/markdown/event_storming.md
> removed slides from beginning of the event storming md file

- slides/markdown/wrap_up.md
- slides/wrap-up.html
resolves issue #420 and can serve as an mvp for wrapping up.
> created new set of slides for wrapping up the class #420

- slides/batch-flow.html
- slides/markdown/batch_flow.md
- slides/markdown/metrics_based_process_mapping.md
resolves issue #411
created a new issue with what to do about batch flow and other things like it. #469
> broke out batch flow from mbpm file

- exercises/1-the-manual-menace/README.md
Just updating some instructions to be explicit that the params_from_cars (ci_cd) needs to be at the top of the file.
cc/ @oybed @springdo @eformat
> Update exercise 1

- exercises/1-the-manual-menace/README.md
🙈🙈🙈
@oybed @tylerauerbeck @gsampaio-rh  @eformat  quick one for ye
🙈🙈🙈
> FIX formatting in ex1

- exercises/1-the-manual-menace/README.md
@tylerauerbeck @springdo @eformat FYI
> Fixing label post-role

- exercises/2-attack-of-the-pipelines/README.md
@tylerauerbeck @oybed @eformat  - bit of a monster change this one, be great if you could take the time to review and mergé if happy 
😉🍭
> 🔥 FIX - exercise 2 being all italic 🔥

- exercises/6-return-of-the-app-monitoring/README.md
@oybed @tylerauerbeck @springdo @eformat
> Fixing todolist-fe to todolist at Ex.6

- exercises/5-non-functionals-strike-back/README.md
@oybed @tylerauerbeck @springdo @eformat
> Adding code snippet for code coverage error at Ex.5

- exercises/3-revenge-of-the-automated-testing/README.md
@eformat @springdo @oybed @tylerauerbeck
> Adding code snippet to Ex.3 at src/components/XofYItems.vue file

- exercises/4-an-enslaved-hope/README.md
Update path part 2 in 4 an enslaved hope.
> FIX path .openshift-applier 4.2

- slides/Dockerfile
> Adds Dockerfile for Slides

- exercises/5-non-functionals-strike-back/README.md
The groovy code in step 5 now matches the "final" code in step 6.
> Added missing url prefix in zap command target

- exercises/0-rogue-cluster/README.md
- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
- exercises/3-revenge-of-the-automated-testing/README.md
- exercises/4-an-enslaved-hope/README.md
- exercises/5-non-functionals-strike-back/README.md
- exercises/6-return-of-the-app-monitoring/README.md
- exercises/README.md
- slides/markdown/continuous_integration_continuous_delivery_continuous_deployment.md
Some small things that clarify the steps
(+ some of my compulsive-obsessive attacks on capitalisation, spelling and punctuation 😬)
> Small improvements

- slides/index.html
... and it's no longer used/needed.
> Remove broken symlink for index.html as it's confusing

- exercises/1-the-manual-menace/README.md
Added how to get to `Source Code Management`
> added a line to direct to Source Code Management

- exercises/1-the-manual-menace/README.md
This is the proper terminology for ansible
> Replace modules for roles

- exercises/1-the-manual-menace/README.md
- exercises/2-attack-of-the-pipelines/README.md
After seeing how things played out in a few virtual runs.
> Small-ish updates and clarifications

- exercises/4-an-enslaved-hope/README.md
Reverts rht-labs/enablement-docs#591
> Revert "removing ocp jenkinsbuild pipeline"

- exercises/index.html
fixes - https://github.com/rht-labs/enablement-docs/issues/305
adds image zoom to all images
> 🐌 add image zoom to all images 🐌

- exercises/index.html
fixes https://github.com/rht-labs/enablement-docs/issues/609
button appears when you hover over code section with mouse.
> 🕷️  add copy button to code section  🕷️

- slides/package.json
> Updated libs

- exercises/1-the-manual-menace/README.md
Exercise 01 has a broken link to FAQ page. This PR includes the fix to the right page.
> Fixing broken link to FAQ page in exercise 01

- README.md
@eformat / @ckavili - Im on for marking this repo read only as we're moving on with our lives in TL500 Land. Once this PR is accepted, I';ll archive the repo
> 🦩 ADD - Depreciation message 🦩
